service: desafio-bgc

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  memorySize: 512

functions:
  scraping:
    handler: srv/scraping.handler
    events: 
      - http: 
          path: /
          method: get

plugins:
  - serverless-plugin-typescript